# 21_roster_pages.py -- code for the notebook section "Roster pages: player photo, number, position, height, class year -- for UWW and every oppo"
# Runs inside the notebook via run_section("21_roster_pages"); its settings are in that notebook cell.

# --- Roster pages: player photo, number, position, height, class year -- for UWW and every opponent ------
# CONFIRMED CHANGE (requested): FastScout has a team roster page separate from the scouting report, at the
# same kind of URL as a team's schedule/games page -- a team's own base URL with "/roster" instead of
# "/games". It shows a photo, jersey number, position, height and class year per player. The user was
# explicit: pull ONLY those bio fields, never any per-game or season stat number that page might also show
# (PPG, RPG, minutes, etc.) -- _ROSTER_STATS_HEADERS below exists specifically to keep that promise, by
# dropping any table that looks like a stat table before any player data is read out of the page at all.
#
# SELECTORS ARE BEST-EFFORT GUESSES, not yet confirmed against a live page (this environment has no
# FastScout credentials or network access to verify against). They are modeled directly on two things this
# notebook already knows for certain:
#   1. The SCHEDULE tab's own pattern (see login_to_fastscout / scrape_rendered_html above): a nav tab
#      clicked by its visible text ("SCHEDULE"), landing in a container with a predictable id
#      ("#myTeamSchedule"). "ROSTER" / "#myTeamRoster" follow that same naming convention.
#   2. The exact bullet-separated player-line format FastScout's OWN PDF roster export already uses --
#      "#<jersey> \u2022 <name> \u2022 <pos> \u2022 <height> \u2022 <weight> \u2022 <class>" (see PLAYER_LINE_RE in the
#      scouting-report PDF parser earlier in this notebook). Since that PDF is generated by FastScout from
#      this same underlying roster data, the live page's player rows are a reasonable bet to carry the same
#      shape. _ROSTER_LINE_RE below is that same pattern, loosened to tolerate different bullet characters
#      and optional weight, and matched against the whole page's flattened text rather than assuming a
#      specific tile/DOM structure -- so it degrades gracefully (matches nothing, rather than matching
#      wrong) if the live markup turns out to differ.
# If either guess is wrong, this cell fails safe: it prints exactly what it tried and why it came back
# empty, and every downstream consumer already treats a missing/empty uww_live_rosters.csv as "no live
# roster yet" (falls back to the sample Personnel Details table), not a hard error.

_ROS_OUT = "uww_live_rosters"
from urllib.parse import unquote  # for decoding the player name FastScout encodes into its photo CDN URLs
_ROSTER_STATS_HEADERS = {
    "pts", "reb", "ast", "stl", "blk", "to", "tov", "pf", "fg", "fg%", "3p", "3p%", "3pt", "ft", "ft%",
    "ppg", "rpg", "apg", "spg", "bpg", "mpg", "gp", "gs", "min", "eff",
}
# Same bullet-separated shape as the PDF roster's PLAYER_LINE_RE, loosened for an unknown live separator
# and an optional weight field between height and class. Height accepts both "6-2" and "6'2\"" spellings.
_ROSTER_LINE_RE = re.compile(
    r"#(\d{1,2})\s*[\u2022|\u00b7]\s*([A-Za-z][A-Za-z.'\-\u00e9\u00f1 ]+?)\s*[\u2022|\u00b7]\s*"
    r"([A-Z]{1,4}(?:/[A-Z]{1,4})?)\s*[\u2022|\u00b7]\s*"
    r"(\d{1,2}[-'\u2019]\d{1,2}\"?)\s*(?:[\u2022|\u00b7]\s*\d{2,3}\s*(?:lbs?)?\s*)?[\u2022|\u00b7]\s*"
    r"([A-Za-z]{2,10})\.?"
)


def _ros_normalize_height(raw):
    """"6'2\"" or "6\u20192" -> "6-2"; "6-2" passes through unchanged -- matches the hyphenated convention
    every other height value in this pipeline already uses."""
    m = re.match(r"(\d{1,2})[-'\u2019](\d{1,2})", str(raw))
    return f"{m.group(1)}-{m.group(2)}" if m else str(raw)


def _ros_norm_name(name):
    return re.sub(r"\s+", " ", str(name)).strip().lower()


# CONFIRMED BY A LIVE RUN: FastScout's headshot CDN URL carries the player's own name in its path --
# "https://stats-assets.fastmodelsports.com/images/personnel/Aurora/2025-2026/Josh%20Tinney/1763067644351"
# -- which means a photo can be attached to a player by NAME, not by which position it happens to occupy on
# the page. That matters because the position-based pairing this cell originally used was confirmed wrong on
# a live run (Mekhi Doby's row carried Josh Tinney's photo), so name-matching replaces it as the primary
# method; positional pairing is now only a fallback, used solely for images whose URL doesn't carry a name
# (already excluded from that fallback pool if it turned out to be a genuine 1:1 correspondence, this would
# be unnecessary -- it isn't, so treat any positionally-assigned photo as lower-confidence than a name match).
_ROSTER_PHOTO_NAME_RE = re.compile(r"/personnel/[^/]+/[^/]+/([^/]+)/[^/]+/?$")


def _ros_photo_owner(url):
    """The player name encoded in a FastScout headshot CDN URL, if the URL has that shape. None for a URL
    that doesn't match -- e.g. a generic silhouette placeholder with no player-specific path."""
    if not url:
        return None
    m = _ROSTER_PHOTO_NAME_RE.search(url)
    if not m:
        return None
    return unquote(m.group(1)).replace("+", " ").strip()


# CONFIRMED BUG (fixed here): the roster page is a JavaScript app -- a saved capture of UW-Whitewater's page
# had the nav chrome, the "PLAYERS PER ROW" toggle and the sort dropdown, and 398 characters of text in total:
# not one player. The old waits looked for "#myTeamRoster", which does not exist on this page at all (the only
# roster-ish id is "roster-page-sort-dropdown"), so both waits timed out and the shell was captured anyway.
# Wait for actual player content instead -- FastScout's own headshot URLs (/images/personnel/...) are the
# reliable tell, with the bullet player line as a backup for a player with no photo.
_ROS_PLAYER_IMG_SELECTOR = "img[src*='/images/personnel/']"


def _ros_wait_for_players(page, timeout_ms=30000):
    """Poll until the roster actually renders. Returns the number of player photos found (-1 when players are
    on the page as text but have no photos, 0 when nothing rendered before the timeout)."""
    try:
        page.wait_for_load_state("networkidle", timeout=timeout_ms)
    except Exception:
        pass
    waited = 0
    while waited < timeout_ms:
        try:
            found = int(page.evaluate(
                f"document.querySelectorAll({_ROS_PLAYER_IMG_SELECTOR!r}).length"))
        except Exception:
            found = 0
        if found:
            return found
        try:
            body_text = page.evaluate("document.body.innerText") or ""
        except Exception:
            body_text = ""
        if re.search(r"#\d{1,2}\s*[\u2022|\u00b7]", body_text):
            return -1
        try:
            page.mouse.wheel(0, 1200)  # nudge anything that renders lazily on scroll
        except Exception:
            pass
        page.wait_for_timeout(500)
        waited += 500
    return 0


def _ros_open_list_view(page):
    """The roster page has a PLAYERS PER ROW toggle; the 1-per-row view lays each player out as a row with his
    number, position, height and class beside the photo, which is the shape this parser reads best."""
    try:
        if page.locator("#players-per-row-1").count():
            page.click("#players-per-row-1", timeout=5000)
            page.wait_for_timeout(750)
    except Exception:
        pass


def _ros_cards_from_dom(soup, team_label):
    """Fallback parse: one row per headshot, taking the player's NAME from the image URL (FastScout encodes it
    there) and the rest from the text around the image. Works when the page renders player details as separate
    elements rather than one bullet-separated line."""
    rows = []
    seen = set()
    for img in soup.select(_ROS_PLAYER_IMG_SELECTOR):
        src = img.get("src") or ""
        owner = _ros_photo_owner(src)
        if not owner or _ros_norm_name(owner) in seen:
            continue
        seen.add(_ros_norm_name(owner))
        node, text = img, ""
        for _ in range(5):  # climb until the surrounding block has more than just the image
            node = node.parent
            if node is None:
                break
            text = node.get_text(" ", strip=True)
            if len(text) > len(owner) + 6:
                break
        jersey = re.search(r"#\s*(\d{1,2})\b", text)
        pos = re.search(r"\b([A-Z]{1,2}(?:/[A-Z]{1,2})?)\b(?!\w)", text.replace(owner, ""))
        height = re.search(r"\b(\d{1,2}[-'\u2019]\d{1,2})\b", text)
        year = re.search(r"\b(Fr|So|Jr|Sr|Gr|R-Fr|R-So|R-Jr|R-Sr)\.?\b", text)
        rows.append({
            "team": team_label, "jersey_number": jersey.group(1) if jersey else None,
            "name": owner, "position": pos.group(1) if pos else None,
            "height": _ros_normalize_height(height.group(1)) if height else None,
            "class_year": year.group(1) if year else None,
            "photo_url": _resolve_team_link(src), "source": "FastScout roster page",
        })
    return rows


def parse_roster_html(html, team_label):
    """Bio fields only, by design: strip any table that looks like a stat table BEFORE reading anything
    else off the page, then regex-match the bullet-separated player lines in the remaining flattened text.
    Photos are attached by the player name encoded in the image's own CDN URL (_ros_photo_owner) whenever
    the URL carries one; page position is used only as a fallback for a photo whose URL doesn't name its
    owner, and that fallback is exactly the case a live run showed CAN mismatch -- so a positionally-assigned
    photo is flagged in the diagnostic count below rather than trusted silently."""
    soup = BeautifulSoup(html, "lxml")
    for tbl in soup.find_all("table"):
        header_text = " ".join(c.get_text(" ", strip=True).lower() for c in tbl.find_all(["th", "td"])[:20])
        header_tokens = set(re.findall(r"[a-z%]+", header_text))
        if header_tokens & _ROSTER_STATS_HEADERS:
            tbl.decompose()

    text = re.sub(r"\s+", " ", soup.get_text(" ", strip=True))
    matches = list(_ROSTER_LINE_RE.finditer(text))
    photo_urls = [
        img.get("src") for img in soup.find_all("img")
        if img.get("src") and not re.search(r"logo|icon|crest|badge", img.get("src"), re.IGNORECASE)
    ]
    photo_by_owner = {}
    unnamed_photos = []
    for _src in photo_urls:
        _owner = _ros_photo_owner(_src)
        if _owner:
            photo_by_owner[_ros_norm_name(_owner)] = _src
        else:
            unnamed_photos.append(_src)
    _unnamed_iter = iter(unnamed_photos)
    _n_by_name = _n_by_position = 0

    rows = []
    seen_jerseys = set()
    for m in matches:
        jersey, name, pos, height_raw, class_year = m.groups()
        # The same bullet line can appear twice if the page repeats a player card (e.g. a "starters" and a
        # "full roster" panel on one page) -- keep the first occurrence only, per team.
        if jersey in seen_jerseys:
            continue
        seen_jerseys.add(jersey)
        _photo = photo_by_owner.get(_ros_norm_name(name))
        if _photo is not None:
            _n_by_name += 1
        else:
            _photo = next(_unnamed_iter, None)
            if _photo is not None:
                _n_by_position += 1
        rows.append({
            "team": team_label, "jersey_number": jersey, "name": name.strip(),
            "position": pos.strip(), "height": _ros_normalize_height(height_raw),
            "class_year": class_year.strip().rstrip("."),
            "photo_url": _resolve_team_link(_photo) if _photo else None,
            "source": "FastScout roster page",
        })
    if _n_by_position:
        print(f"    [roster] {team_label}: {_n_by_name} photo(s) matched by name in the URL, "
              f"{_n_by_position} fell back to page position (lower confidence -- spot-check these).")
    if not rows:
        rows = _ros_cards_from_dom(soup, team_label)
        if rows:
            print(f"    [roster] {team_label}: no bullet-separated player lines on this page -- read "
                  f"{len(rows)} player(s) from the headshot URLs and the text around them instead.")
    return pd.DataFrame(rows, columns=["team", "jersey_number", "name", "position", "height", "class_year",
                                       "photo_url", "source"])


def scrape_roster_rendered_html(page, url, wait_selector=None, timeout_ms=30000, save_path=None):
    """Live-scrape one team's roster page: navigate to its base team URL, click the 'ROSTER' nav tab (see
    _click_tab_by_text -- a direct URL to the sub-route doesn't render it, same as '/games'/'/documents'),
    then read the rendered HTML. Falls back to returning whatever HTML is on screen if wait_selector's
    guessed id never appears, rather than failing outright on a selector guess that may be wrong."""
    print(f"    [scrape] navigating to {url}")
    _goto_with_auth_retry(page, url, "text=ROSTER", timeout_ms)
    print(f"    [scrape] landed on {page.url} -- clicking 'ROSTER' tab")
    _click_tab_by_text(page, "ROSTER", timeout_ms)
    _ros_open_list_view(page)
    _found = _ros_wait_for_players(page, timeout_ms)
    if _found == 0:
        print(f"    [scrape] no player photos or player lines rendered within {timeout_ms}ms -- capturing the "
              f"page anyway, but expect this team to come back with no roster rows.")
    html = page.content()
    if save_path:
        _save_scraped_html(html, _add_season_suffix_to_path(save_path, html), "roster page")
    return html


def scrape_uww_live_roster(page, timeout_ms=30000, save_path=None):
    """UWW's own roster -- assumes page is already on an authenticated team page (post-login), same
    assumption scrape_uww_live_schedule makes for the SCHEDULE tab."""
    print("    [scrape] clicking 'ROSTER' tab")
    _click_tab_by_text(page, "ROSTER", timeout_ms)
    _ros_open_list_view(page)
    _found = _ros_wait_for_players(page, timeout_ms)
    if _found == 0:
        print(f"    [scrape] no player photos or player lines rendered within {timeout_ms}ms -- capturing the "
              f"page anyway, but expect this team to come back with no roster rows.")
    html = page.content()
    if save_path:
        _save_scraped_html(html, _add_season_suffix_to_path(save_path, html), "UW-Whitewater's own roster")
    return html


def _ros_local_backup(team_label):
    """A previously-saved roster snapshot for this team, either a genuine MHTML export or this cell's own
    live-scrape cache -- same skip-the-live-scrape-if-we-already-have-one convention as the schedule cell."""
    key = team_label.split()[0].lower()
    for p in sorted(glob.glob(f"{schedules_dir}/*.html") + glob.glob(f"{schedules_dir}/*.mhtml")):
        base = os.path.basename(p)
        if re.search(r"-\s*Roster", base, re.IGNORECASE) and key in base.lower():
            return p
    return None


_ros_problems = []

# CONFIRMED BUG (fixed here): UWW came back with ZERO roster rows while every opponent scraped fine. UWW was
# the one target with no URL -- it clicked "ROSTER" on whatever page the session already had open, which after
# login_to_fastscout is ".../teams/myTeam/analytics/dashboard". That ANALYTICS view has its own sub-nav and no
# ROSTER tab, so the click failed, the per-target except swallowed it, and our own players silently had no
# photos in the brief. UWW now navigates to its own TEAM page first, exactly like every opponent does -- the
# "myTeam" alias works in that URL the same way it does for the dashboard.
#
# Targets: UWW itself, every opponent already resolved for the schedule (the `opponents` DataFrame built
# above), plus the upcoming opponent specifically -- `opponents` only covers SCOUTED games, so with
# before_scout="yes" the upcoming opponent would otherwise be skipped even though their roster is exactly
# what's needed to prep for them.
_ROS_UWW_URL = (f"{FASTSCOUT_ORIGIN}/teams/myTeam?league={FASTSCOUT_DOCS_LEAGUE}&season={FASTSCOUT_DOCS_SEASON}")
_ros_targets = [(uww_team_schedule["team"].iloc[0] if not uww_team_schedule.empty else "UW-Whitewater",
                 _ROS_UWW_URL)]
if not opponents.empty:
    for _, _r in opponents.iterrows():
        _ros_targets.append((_r["opponent"], _r["opponent_url"]))
if upcoming_opponent and upcoming_opponent not in {t for t, _ in _ros_targets}:
    _up_rows = raw_uww_games[raw_uww_games["opponent"] == upcoming_opponent] if "raw_uww_games" in dir() else pd.DataFrame()
    if not _up_rows.empty and pd.notna(_up_rows.iloc[0].get("opponent_url")):
        _ros_targets.append((upcoming_opponent, _up_rows.iloc[0]["opponent_url"]))
    else:
        _ros_problems.append(f"could not resolve a team URL for the upcoming opponent ({upcoming_opponent}) "
                             f"-- their roster was skipped this run.")

_seen_teams = set()
_ros_targets = [t for t in _ros_targets if not (t[0] in _seen_teams or _seen_teams.add(t[0]))]
print(f"Roster targets this run: {[t for t, _ in _ros_targets]}")


def _run_roster_scrape_session(login_page):
    results = {}
    for _team_label, _team_url in _ros_targets:
        if _ros_local_backup(_team_label):
            print(f"  Skipping live roster scrape for {_team_label} -- a local roster file already exists.")
            continue
        try:
            _save_path = os.path.join(schedules_dir, f"{_team_label} - Roster.html")
            if _team_url is None:
                results[_team_label] = scrape_uww_live_roster(login_page, save_path=_save_path)
            else:
                try:
                    results[_team_label] = scrape_roster_rendered_html(login_page, _team_url, save_path=_save_path)
                except Exception as _nav_error:
                    if _team_url != _ROS_UWW_URL:
                        raise
                    # Our own team only: if the "myTeam" team-page URL doesn't take, fall back to clicking
                    # ROSTER on whatever authenticated page the session already has open.
                    print(f"  {_team_label}: team-page URL didn't work ({type(_nav_error).__name__}: "
                          f"{_nav_error}) -- trying the ROSTER tab on the current page instead.")
                    results[_team_label] = scrape_uww_live_roster(login_page, save_path=_save_path)
        except Exception as _scrape_error:
            # Loud, not swallowed: a failure here is why a team ends up with no photos at all, and the brief
            # can only report the symptom.
            _ros_problems.append(f"{_team_label}: roster scrape failed ({type(_scrape_error).__name__}: "
                                 f"{_scrape_error}) -- no photos or bio details for this team this run.")
            print(f"  Could not scrape roster for {_team_label}: {type(_scrape_error).__name__}: {_scrape_error}")
    return results


scraped_roster_html = {}
if not (fastscout_username and fastscout_password):
    _ros_problems.append("no FastScout credentials (FASTSCOUT_USERNAME/FASTSCOUT_PASSWORD) -- live roster "
                         "scrape skipped for every team; only local ' - Roster' backups (if any) were used.")
elif not _ros_targets:
    _ros_problems.append("no roster targets resolved (no schedule loaded yet) -- nothing to scrape.")
else:
    try:
        scraped_roster_html = run_in_fastscout_session(_run_roster_scrape_session)
    except Exception as _session_error:
        _ros_problems.append(f"could not start an authenticated FastScout session for rosters: "
                             f"{type(_session_error).__name__}: {_session_error}")

_ros_frames = []
for _team_label, _team_url in _ros_targets:
    _html = scraped_roster_html.get(_team_label)
    if _html is None:
        _backup = _ros_local_backup(_team_label)
        if _backup:
            _html = load_html_snapshot(_backup)
    if _html is None:
        continue
    try:
        _parsed = parse_roster_html(_html, _team_label)
        if _parsed.empty:
            _ros_problems.append(f"{_team_label}: page loaded but no player lines matched the expected "
                                 f"bullet pattern -- the live page's format likely differs from the PDF "
                                 f"roster's; _ROSTER_LINE_RE needs adjusting once the real markup is visible.")
        _ros_frames.append(_parsed)
    except Exception as _parse_error:
        _ros_problems.append(f"{_team_label}: could not parse roster HTML: "
                             f"{type(_parse_error).__name__}: {_parse_error}")

live_rosters = (pd.concat(_ros_frames, ignore_index=True) if _ros_frames else
               pd.DataFrame(columns=["team", "jersey_number", "name", "position", "height", "class_year",
                                     "photo_url", "source"]))

print(f"\nlive_rosters: {len(live_rosters)} player(s) across {live_rosters['team'].nunique() if not live_rosters.empty else 0} team(s).")
for _team_label, _ in _ros_targets:
    _n = int((live_rosters["team"] == _team_label).sum()) if not live_rosters.empty else 0
    if _n == 0:
        print(f"  {_team_label}: NO roster rows -- check the saved '{_team_label} - Roster.html' in "
              f"{schedules_dir} to see what the page actually returned.")
if not live_rosters.empty:
    _show(live_rosters.groupby("team").size())
if _ros_problems:
    print("\nRoster problems:")
    for _p in _ros_problems:
        print(f"  - {_p}")
